### ISSUE TITLE
Can't find ./scripts/run.sh

### ISSUE THREAD

**Issue by gavinzhang333** [ofey404/WalkingShadows#27]
Can't find ./scripts/run.sh

**Comment by gavinzhang333** [comment]
Keep going with this project, and I am very interested in your idea and your project, and thx for your contribution.

**Comment by ofey404** [comment]
> Keep going with this project, and I am very interested in your idea and your project, and thx for your contribution.

I'm doing some prompt engineering about storytelling in `experiments/` now, and I feel like a breakthrough is near.
